from __future__ import annotations

from typing import TYPE_CHECKING

from BaseClasses import Item, ItemClassification

if TYPE_CHECKING:
    from .world import TeardownWorld

ITEM_NAME_TO_ID = {
    "Sledge": 1,
    "Extinguisher": 2,
    "Leaf Blower": 3,
    "Blowtorch": 4,
    "Plank": 5,
    "Cable": 6,
    "Shotgun": 7,
    "Gun": 8,
    "Hunting Rifle": 9,
    "Pipe Bomb": 10,
    "Bomb": 11,
    "Rocket": 12,
    "Nitroglycerin": 13,
    "Rocket Booster": 14,
    "Vehicle Thruster": 15,
    "BlueTide": 16,
    "Progressive Leaf Blower Power": 17,
    "Progressive Blowtorch Ammo": 18,
    "Progressive Plank Ammo": 19,
    "Progressive Plank Width": 20,
    "Progressive Plank Length": 21,
    "Progressive Cable Ammo": 22,
    "Progressive Cable Stretch": 23,
    "Progressive Shotgun Ammo": 24,
    "Progressive Shotgun Range": 25,
    "Progressive Shotgun Damage": 26,
    "Progressive Gun Ammo": 27,
    "Progressive Gun Range": 28,
    "Progressive Gun Damage": 29,
    "Progressive Hunting Rifle Ammo": 30,
    "Progressive Pipe Bomb Ammo": 31,
    "Progressive Pipe Bomb Damage": 32,
    "Progressive Bomb Ammo": 33,
    "Progressive Bomb Damage": 34,
    "Progressive Rocket Ammo": 35,
    "Progressive Rocket Damage": 36,
    "Progressive Nitroglycerin Ammo": 37,
    "Progressive Nitroglycerin Damage": 38,
    "Progressive Rocket Booster Ammo": 39,
    "Progressive Rocket Booster Power": 40,
    "Progressive Rocket Booster Time": 41,
    "Progressive Vehicle Thruster Ammo": 42,
    "Progressive Vehicle Thruster Power": 43,
    "Progressive BlueTide Ammo": 44,
    "Progressive BlueTide Time": 45,
    "Spray can": 46,
    "Debt": 47
}

DEFAULT_ITEM_CLASSIFICATIONS = {
    "Sledge": ItemClassification.progression,
    "Extinguisher": ItemClassification.progression,
    "Leaf Blower": ItemClassification.useful,
    "Blowtorch": ItemClassification.progression,
    "Plank": ItemClassification.progression,
    "Cable": ItemClassification.useful,
    "Shotgun": ItemClassification.progression,
    "Gun": ItemClassification.useful,
    "Hunting Rifle": ItemClassification.useful,
    "Pipe Bomb": ItemClassification.progression,
    "Bomb": ItemClassification.progression,
    "Rocket": ItemClassification.useful,
    "Nitroglycerin": ItemClassification.useful,
    "Rocket Booster": ItemClassification.useful,
    "Vehicle Thruster": ItemClassification.useful,
    "BlueTide": ItemClassification.useful,
    "Progressive Leaf Blower Power": ItemClassification.useful,
    "Progressive Blowtorch Ammo": ItemClassification.useful,
    "Progressive Plank Ammo": ItemClassification.useful,
    "Progressive Plank Width": ItemClassification.useful,
    "Progressive Plank Length": ItemClassification.useful,
    "Progressive Cable Ammo": ItemClassification.useful,
    "Progressive Cable Stretch": ItemClassification.useful,
    "Progressive Shotgun Ammo": ItemClassification.useful,
    "Progressive Shotgun Range": ItemClassification.useful,
    "Progressive Shotgun Damage": ItemClassification.useful,
    "Progressive Gun Ammo": ItemClassification.useful,
    "Progressive Gun Range": ItemClassification.useful,
    "Progressive Gun Damage": ItemClassification.useful,
    "Progressive Hunting Rifle Ammo": ItemClassification.useful,
    "Progressive Pipe Bomb Ammo": ItemClassification.useful,
    "Progressive Pipe Bomb Damage": ItemClassification.useful,
    "Progressive Bomb Ammo": ItemClassification.useful,
    "Progressive Bomb Damage": ItemClassification.useful,
    "Progressive Rocket Ammo": ItemClassification.useful,
    "Progressive Rocket Damage": ItemClassification.useful,
    "Progressive Nitroglycerin Ammo": ItemClassification.useful,
    "Progressive Nitroglycerin Damage": ItemClassification.useful,
    "Progressive Rocket Booster Ammo": ItemClassification.useful,
    "Progressive Rocket Booster Power": ItemClassification.useful,
    "Progressive Rocket Booster Time": ItemClassification.useful,
    "Progressive Vehicle Thruster Ammo": ItemClassification.useful,
    "Progressive Vehicle Thruster Power": ItemClassification.useful,
    "Progressive BlueTide Ammo": ItemClassification.useful,
    "Progressive BlueTide Time": ItemClassification.useful,
    "Debt": ItemClassification.filler,
    "Spray can": ItemClassification.useful
}

class TeardownItem(Item):
    game = "Teardown"

def get_random_filler_item_name(world: APQuestWorld) -> str:
    return "Debt"

def create_item_with_correct_classification(world: TeardownWorld, name: str) -> TeardownItem:

    classification = DEFAULT_ITEM_CLASSIFICATIONS[name]

    return TeardownItem(name, classification, ITEM_NAME_TO_ID[name], world.player)

def create_all_items(world: TeardownWorld) -> None:

    itempool: list[Item] = [
        world.create_item("Sledge"),
        world.create_item("Extinguisher"),
        world.create_item("Leaf Blower"),
        world.create_item("Blowtorch"),
        world.create_item("Plank"),
        world.create_item("Cable"),
        world.create_item("Shotgun"),
        world.create_item("Gun"),
        world.create_item("Hunting Rifle"),
        world.create_item("Pipe Bomb"),
        world.create_item("Bomb"),
        world.create_item("Rocket"),
        world.create_item("Nitroglycerin"),
        world.create_item("Rocket Booster"),
        world.create_item("Vehicle Thruster"),
        world.create_item("BlueTide"),
        world.create_item("Progressive Leaf Blower Power"),
        world.create_item("Progressive Leaf Blower Power"),
        world.create_item("Progressive Leaf Blower Power"),
        world.create_item("Progressive Blowtorch Ammo"),
        world.create_item("Progressive Blowtorch Ammo"),
        world.create_item("Progressive Blowtorch Ammo"),
        world.create_item("Progressive Blowtorch Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Ammo"),
        world.create_item("Progressive Plank Width"),
        world.create_item("Progressive Plank Width"),
        world.create_item("Progressive Plank Length"),
        world.create_item("Progressive Plank Length"),
        world.create_item("Progressive Plank Length"),
        world.create_item("Progressive Cable Ammo"),
        world.create_item("Progressive Cable Ammo"),
        world.create_item("Progressive Cable Ammo"),
        world.create_item("Progressive Cable Stretch"),
        world.create_item("Progressive Cable Stretch"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Ammo"),
        world.create_item("Progressive Shotgun Range"),
        world.create_item("Progressive Shotgun Range"),
        world.create_item("Progressive Shotgun Damage"),
        world.create_item("Progressive Shotgun Damage"),
        world.create_item("Progressive Gun Ammo"),
        world.create_item("Progressive Gun Ammo"),
        world.create_item("Progressive Gun Ammo"),
        world.create_item("Progressive Gun Ammo"),
        world.create_item("Progressive Gun Ammo"),
        world.create_item("Progressive Gun Range"),
        world.create_item("Progressive Gun Range"),
        world.create_item("Progressive Gun Range"),
        world.create_item("Progressive Gun Damage"),
        world.create_item("Progressive Gun Damage"),
        world.create_item("Progressive Hunting Rifle Ammo"),
        world.create_item("Progressive Hunting Rifle Ammo"),
        world.create_item("Progressive Pipe Bomb Ammo"),
        world.create_item("Progressive Pipe Bomb Ammo"),
        world.create_item("Progressive Pipe Bomb Ammo"),
        world.create_item("Progressive Pipe Bomb Ammo"),
        world.create_item("Progressive Pipe Bomb Ammo"),
        world.create_item("Progressive Pipe Bomb Damage"),
        world.create_item("Progressive Pipe Bomb Damage"),
        world.create_item("Progressive Bomb Ammo"),
        world.create_item("Progressive Bomb Ammo"),
        world.create_item("Progressive Bomb Ammo"),
        world.create_item("Progressive Bomb Ammo"),
        world.create_item("Progressive Bomb Ammo"),
        world.create_item("Progressive Bomb Damage"),
        world.create_item("Progressive Bomb Damage"),
        world.create_item("Progressive Rocket Ammo"),
        world.create_item("Progressive Rocket Ammo"),
        world.create_item("Progressive Rocket Ammo"),
        world.create_item("Progressive Rocket Damage"),
        world.create_item("Progressive Rocket Damage"),
        world.create_item("Progressive Nitroglycerin Ammo"),
        world.create_item("Progressive Nitroglycerin Ammo"),
        world.create_item("Progressive Nitroglycerin Ammo"),
        world.create_item("Progressive Nitroglycerin Damage"),
        world.create_item("Progressive Nitroglycerin Damage"),
        world.create_item("Progressive Nitroglycerin Damage"),
        world.create_item("Progressive Rocket Booster Ammo"),
        world.create_item("Progressive Rocket Booster Ammo"),
        world.create_item("Progressive Rocket Booster Ammo"),
        world.create_item("Progressive Rocket Booster Power"),
        world.create_item("Progressive Rocket Booster Power"),
        world.create_item("Progressive Rocket Booster Time"),
        world.create_item("Progressive Rocket Booster Time"),
        world.create_item("Progressive Vehicle Thruster Ammo"),
        world.create_item("Progressive Vehicle Thruster Ammo"),
        world.create_item("Progressive Vehicle Thruster Ammo"),
        world.create_item("Progressive Vehicle Thruster Power"),
        world.create_item("Progressive Vehicle Thruster Power"),
        world.create_item("Progressive BlueTide Ammo"),
        world.create_item("Progressive BlueTide Ammo"),
        world.create_item("Progressive BlueTide Time"),
        world.create_item("Progressive BlueTide Time"),
        world.create_item("Spray can"),
    ]

    number_of_items = len(itempool)

    number_of_unfilled_locations = len(world.multiworld.get_unfilled_locations(world.player))

    needed_number_of_filler_items = number_of_unfilled_locations - number_of_items

    itempool += [world.create_filler() for _ in range(needed_number_of_filler_items)]

    world.multiworld.itempool += itempool

    if world.options.start_with_spray_can:
        starting_spray_can = world.create_item("Spray can")
        world.push_precollected(starting_spray_can)
